- name: Setup .NET Core # Required to execute ReportGenerator
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 6.x
    dotnet-quality: 'ga'

- name: ReportGenerator
  uses: danielpalme/ReportGenerator-GitHub-Action@5.1.23
  with:
    reports: cobertura.xml
    targetdir: /coveragereport
    reporttypes: Html;MarkdownSummaryGithub
    sourcedirs: /
    historydir: /coveragereport
    license: MIT
